# unshare provider: base + iptables, iproute2, slirp4netns.
# Build: make build-image-unshare  =>  python-sb-unshare:$(PYTHON_VERSION), python-sb-unshare:latest
ARG PYTHON_VERSION=3.11
FROM python-sb:${PYTHON_VERSION}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    iptables \
    iproute2 \
    slirp4netns && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

CMD ["python-sb"]
