# landlock provider: base only (Landlock is a kernel LSM, no package to install).
# Build: make build-image-landlock  =>  python-sb-landlock:$(PYTHON_VERSION), python-sb-landlock:latest
ARG PYTHON_VERSION=3.11
FROM python-sb:${PYTHON_VERSION}
