# IMPORTANT: This module must be imported *before* any other modules that might
# use the standard `socket` library in your application's main entry point.
#
# Purpose:
# This module patches the standard `socket.socket` class with a custom
# `Guard_socket` class. Its primary role is to intercept and protect network
# socket calls made by Python code using the standard `socket` interface.
#
# Activation:
# The patching happens automatically when this module is imported. To ensure
# that all subsequent uses of `socket.socket` throughout your application
# (including those within third-party libraries) are guarded, this import
# MUST occur before those modules are imported.
#
# Scope of Protection:
# This guard protects against direct socket usage via the Python `socket`
# module. It is designed to mitigate risks from potentially malicious or
# unintended network access originating from Python code, such as code
# generated by an LLM.
#
# Limitations:
# This protection is easily bypassable. It does NOT protect against:
# - Network calls made by native shared libraries (e.g., C/C++ code) invoked
#   by Python.
# - Network calls made by child processes spawned by the Python application.
# - Other forms of inter-process communication.
#
# Nature of Security:
# This is a best-effort security layer within the Python process itself. It
# is NOT a robust security boundary like a firewall, containerization, or
# OS-level sandboxing. It is intended to limit the attack surface specifically
# from potentially untrusted Python code executed within the same process.
#
# Example Usage (in your main application file, e.g., main.py):
# import langgraph_codeagent.sandboxes.guard_socket
# # Now import other modules that use sockets (e.g., requests, urllib, etc.)
# import requests
# import urllib.request
# # ... rest of your application code ...

import ipaddress
import logging
from random import choice
from string import ascii_uppercase
from typing import Tuple, Optional, Union, List

import socket

# Address format details can be found in the Python socket library documentation:
# https://docs.python.org/3/library/socket.html#address-families
Adresse_Type = Union[
    str,  # For AF_UNIX sockets
    Tuple[str, int],  # For AF_INET, AF_BLUETOOTH, AF_PACKET, AF_RDS sockets
    Tuple[str, int, int, int],  # For AF_INET6 sockets
    Tuple[int, bytes],  # For AF_NETLINK sockets
    Tuple[str],  # For AF_CAN, PF_SYSTEM sockets
    Tuple[str, str],  # For AF_ALG sockets
    Tuple[int, int],  # For AF_VSOCK, AF_QIPCRTR sockets
    Tuple[int, int, int, int, int]  # For AF_TIPC sockets
]

DENY = "DENY"  # Action to deny a connection
ALLOW = "ALLOW"  # Action to allow a connection
IN = "IN"  # Direction for incoming connections (e.g., server-side bind)
OUT = "OUT"  # Direction for outgoing connections (e.g., client-side connect)

# Rule format: (action, network_spec_str, direction_str)
# action: str (DENY or ALLOW)
# network_spec_str: str (e.g., "192.168.1.0/24:80,443" or "0.0.0.0/0:*")
# direction_str: str (IN or OUT)
Rule = Tuple[str, str, str]

# Parsed rule format used internally: (action_str, (ipaddress.ip_network, Union[List[int], range]), direction_str)
ParsedRule = Tuple[str, Tuple[ipaddress.ip_network, Union[List[int], range]], str]


logger = logging.getLogger(__name__)

_get_rules = lambda: []  # Placeholder for initial state, returns an empty list of rules


def _convert_ports_range(syntaxe: str) -> Union[List[int], range]:
    """
    Converts a port specification string (e.g., "80,443,8000-8080,*")
    into a sorted list of unique integer port numbers or a range object for '*'.

    Args:
        syntaxe: The port specification string.

    Returns:
        A sorted list of integers representing individual ports and expanded ranges,
        or a range(0, 65536) if '*' is specified. Returns an empty list for invalid syntax.
    """
    if not syntaxe:
        return []
    if syntaxe.strip() == '*':
        return range(65536)  # Represents all ports
    ports = set()
    max_port = 65535  # Maximum valid port number
    elements = syntaxe.split(',')
    for element in elements:
        element = element.strip()
        if not element:
            continue
        if '-' in element:
            limites = element.split('-', 1)
            if len(limites) == 2:
                debut_str, end_str = limites[0].strip(), limites[1].strip()
                if not debut_str:
                    logger.warning(
                        f"Invalid range format: '{element}'. Range start cannot be empty.")
                    return []  # Invalid format
                try:
                    start = int(debut_str)
                except ValueError:
                    logger.warning(
                        f"Invalid start port number '{debut_str}' in range '{element}'.")
                    return []  # Invalid start port
                if not (0 <= start <= max_port):
                    logger.warning(
                        f"Start port {start} in range '{element}' is out of valid range (0-{max_port}).")
                    return []  # Start port out of range

                if end_str == '': # Handles open-ended ranges like "8000-"
                    end = max_port
                else:
                    try:
                        end = int(end_str)
                    except ValueError:
                        logger.warning(
                            f"Invalid end port number '{end_str}' in range '{element}'.")
                        return []  # Invalid end port
                    if not (0 <= end <= max_port):
                        logger.warning(
                            f"End port {end} in range '{element}' is out of valid range (0-{max_port}).")
                        return []  # End port out of range
                if start <= end:
                    ports.update(range(start, end + 1))
                else:
                    logger.warning(
                        f"Invalid range: start port {start} is greater than end port {end} in '{element}'.")
                    return []  # Invalid range order
            else:
                logger.warning(
                    f"Invalid range format: '{element}'. Unexpected hyphen usage.")
                return []  # Malformed range
        else:
            try:
                port = int(element)
                if not (0 <= port <= max_port):
                    logger.warning(
                        f"Port number {port} in '{element}' is out of valid range (0-{max_port}).")
                    return []  # Port out of range
                ports.add(port)
            except ValueError:
                logger.warning(f"Invalid port number '{element}'.")
                return []  # Invalid port number
    return sorted(list(ports))

def _check_address_with_rules(
        rules: List[ParsedRule],
        address: Tuple[str, int], # Expect (hostname_or_ip_str, port_int)
        conn_direction: str): # Expect IN or OUT constants
    """
    Checks if a given address and port are allowed for the specified connection direction
    based on the configured rules and the derived implicit default policy.

    The rule evaluation logic is as follows:
    1. If `rules` is empty, all connections are ALLOWED.
    2. Determine the implicit default action:
       - If the first rule in `rules` is ALLOW, the implicit default is DENY.
       - If the first rule in `rules` is DENY, the implicit default is ALLOW.
    3. Determine the order of rule application (`order_apply`):
       - If implicit default is DENY (first rule ALLOW), check DENY rules then ALLOW rules.
       - If implicit default is ALLOW (first rule DENY), check ALLOW rules then DENY rules.
    4. Iterate through resolved IP addresses for the given hostname:
       - For each IP, iterate through rules in the `order_apply` sequence:
         - If a DENY rule matches (IP, port, direction), raise RuntimeError (DENIED).
         - If an ALLOW rule matches (IP, port, direction), raise RuntimeError (ALLOWED).
           (Note: Both explicit ALLOW and DENY raise exceptions to halt further processing
            and clearly state the outcome based on the matched rule.)
    5. If no explicit rule caused an exception:
       - If the implicit default is DENY, raise RuntimeError (DENIED by implicit default).
       - If the implicit default is ALLOW, return (implicitly ALLOWED).

    Args:
        rules: A list of parsed rule tuples.
        address: A tuple containing the hostname/IP string and port number.
        conn_direction: The direction of the connection, either IN or OUT.
    Raises:
        ValueError: If hostname resolution fails, no valid IPs are found, or the port is invalid.
        RuntimeError: If the connection is disallowed by an explicit rule or the implicit default,
                      or if it's explicitly allowed by a rule.
    """
    logger.debug("_check_address_with_rules(address=%s, conn_direction=%s)",
                 address, conn_direction)
    hostname, destination_port = address

    if not isinstance(destination_port, int) or not (
            0 <= destination_port <= 65535):
        raise ValueError(f"Invalid port number: {destination_port}")

    try:
        # Resolve hostname to IP addresses. Using proto=socket.IPPROTO_TCP to be specific.
        infos = socket.getaddrinfo(hostname, None, proto=socket.IPPROTO_TCP)
    except socket.gaierror:
        raise ValueError(
            f"Invalid hostname or IP address (resolution failed): {hostname}")

    ip_objects = []
    for family, _, _, _, sockaddr in infos:
        # sockaddr[0] is the IP address string
        addr_str = sockaddr[0]
        try:
            ip_objects.append(ipaddress.ip_address(addr_str))
        except ValueError:
            # Log and skip if an address from getaddrinfo is not a valid IP
            # (e.g., could happen with link-local IPv6 zone IDs if not handled properly,
            # though ipaddress module usually handles common cases)
            logger.warning(
                f"Could not parse IP address '{addr_str}' from getaddrinfo result "
                f"for '{hostname}'.")
            continue

    # Use dict.fromkeys to get unique IP objects while preserving order (though order isn't critical here)
    unique_ips = list(dict.fromkeys(ip_objects))
    if not unique_ips:
        raise ValueError(
            f"Could not resolve {hostname} to any valid IP address for "
            f"rule checking.")

    if not rules:  # Case 1: No rules set
        logger.info(
            f"Connection to {hostname} (resolved to {unique_ips}) "
            f"port {destination_port} ALLOWED because no rules are set "
            f"(fallback to allow by default)."
        )
        return  # ALLOWED

    # Case 2: Determine implicit default based on the first rule
    first_rule_action = rules[0][0]  # action is the first element of the parsed rule tuple

    # Determine the order of applying DENY/ALLOW checks based on the first rule's action.
    # If the first rule is ALLOW, implicit default is DENY. We check DENY rules first.
    # If the first rule is DENY, implicit default is ALLOW. We check ALLOW rules first.
    order_apply = (DENY, ALLOW) if first_rule_action == ALLOW else (ALLOW, DENY)
    implicit_default_is_deny = (first_rule_action == ALLOW)

    logger.debug(
        f"First rule is {first_rule_action}, so rule check order is {order_apply}, "
        f"and implicit default for non-matching connections is {'DENY' if implicit_default_is_deny else 'ALLOW'}.")

    # Iterate through DENY/ALLOW based on determined order
    for rule_type_to_check in order_apply:
        for ip_host in unique_ips: # Check each resolved IP
            for rule_idx, (action, (network_obj, rule_ports_list),
                           rule_direction_from_rule) in enumerate(rules):
                # Only consider rules of the current type being checked (DENY or ALLOW)
                if action == rule_type_to_check:
                    if rule_direction_from_rule == conn_direction: # Match direction
                        if ip_host in network_obj and destination_port in rule_ports_list: # Match network and port
                            # Explicit rule matched
                            log_message = (
                                f"Connection to {hostname} ({ip_host}:{destination_port}) "
                                f"{action} by explicit rule #{rule_idx}: "
                                f"{action} net={network_obj} ports={rule_ports_list} "
                                f"dir={conn_direction}"
                            )
                            logger.info(log_message)
                            # Both explicit ALLOW and DENY raise an exception to stop processing
                            # and clearly indicate the decision.
                            raise RuntimeError(
                                f"Guard network connection to "
                                f"{ip_host}:{destination_port} (from {hostname}) "
                                f"explicitly {action} by rule #{rule_idx} "
                                f"({action} {network_obj}:{rule_ports_list} "
                                f"{conn_direction})."
                            )

    # Case 5: No explicit rule matched (neither DENY nor ALLOW caused an exception)
    # Apply the implicit default.
    if implicit_default_is_deny:
        logger.info(
            f"Connection to {hostname} (resolved to {unique_ips}) port {destination_port} "
            f"DENIED by implicit default policy (first rule was {first_rule_action}, "
            f"no other rule explicitly matched)."
        )
        raise RuntimeError(
            f"Guard network connection to {hostname} (port {destination_port}) "
            f"DENIED by implicit default (first rule: {first_rule_action}). Resolved IPs: {unique_ips}"
        )
    else:  # implicit_default_is_allow
        logger.info(
            f"Connection to {hostname} (resolved to {unique_ips}) port {destination_port} "
            f"ALLOWED by implicit default policy (first rule was {first_rule_action}, "
            f"no other rule explicitly matched)."
        )
        return  # ALLOWED

_get_rules = lambda: []  # Re-initialize placeholder for Guard_socket class context

class Guard_socket(socket.socket):
    """
    A custom socket class that enforces network rules to restrict connections.

    Rule Evaluation Logic:
    1. If no rules are configured, all connections are ALLOWED (fallback behavior).
    2. If rules are configured:
       a. The implicit default action is determined by the first rule:
          - If the first rule is ALLOW, the implicit default for non-matching connections is DENY.
          - If the first rule is DENY, the implicit default for non-matching connections is ALLOW.
       b. Rule checking order depends on the implicit default:
          - If implicit default is DENY (first rule ALLOW): DENY rules are checked first, then ALLOW rules.
          - If implicit default is ALLOW (first rule DENY): ALLOW rules are checked first, then DENY rules.
       c. For any connection attempt (to a specific hostname and port):
          i. The hostname is resolved to one or more IP addresses.
         ii. Each IP address is checked against the rules in the determined order.
        iii. If a DENY rule matches any resolved IP, port, and direction, the connection is
             immediately DENIED (RuntimeError is raised).
         iv. If an ALLOW rule matches any resolved IP, port, and direction (and no preceding DENY
             rule matched in its check phase), the connection is immediately ALLOWED (RuntimeError
             is raised to indicate explicit allowance).
          v. If no rule explicitly DENIES or ALLOWS the connection after checking all resolved IPs
             against all relevant rules, the implicit default action (determined in step 2a) is applied.
             If implicitly DENIED, a RuntimeError is raised. If implicitly ALLOWED, the operation proceeds.
    """

    @classmethod
    def set_rules(cls, rules: List[Rule]):
        """
        Sets the network rules for the Guard_socket.
        This method is designed to be called once to prevent rule tampering during runtime.

        Args:
            rules: A list of Rule tuples. Each rule is (action_str, network_spec_str, direction_str).
                   action_str: DENY or ALLOW (string constants).
                   network_spec_str: A string like "ip_network/prefix:port_spec"
                                     (e.g., "192.168.1.0/24:80,443" or "0.0.0.0/0:*").
                   direction_str: IN or OUT (string constants).
        Raises:
            ValueError: If rules have already been set or if any rule is malformed
                        (invalid format, action, direction, network, or port specification).
        """
        # Generate a random internal name to store parsed rules, making it harder to access directly.
        random_rules_name = "_rules_storage_" + ''.join(choice(ascii_uppercase) for _ in range(12))
        if cls.__dict__.get("get_rules", _get_rules) == _get_rules: # Check if it's the initial placeholder
            parsed_rules: List[ParsedRule] = []
            for i, rule_tuple in enumerate(rules):
                if not (isinstance(rule_tuple, tuple) and len(rule_tuple) == 3):
                    raise ValueError(f"Rule {i} is not a valid 3-tuple: {rule_tuple}")

                action, rule_spec, direction = rule_tuple

                if action not in (DENY, ALLOW):
                    raise ValueError(
                        f"Rule {i} action '{action}' is not '{ALLOW}' or '{DENY}'. Rule: {rule_tuple}")
                if not isinstance(rule_spec, str):
                    raise ValueError(
                        f"Rule {i} network_spec '{rule_spec}' is not a string. Rule: {rule_tuple}")
                if direction not in (IN, OUT):
                    raise ValueError(
                        f"Rule {i} direction '{direction}' is not '{IN}' or '{OUT}'. Rule: {rule_tuple}")

                if ':' not in rule_spec:
                    raise ValueError(
                        f"Invalid rule format for rule {i} ('{rule_spec}'): must contain ':' separating network and port spec.")
                network_str, port_spec = rule_spec.rsplit(':', 1)

                try:
                    network = ipaddress.ip_network(network_str, strict=False)
                except ValueError as e:
                    raise ValueError(
                        f"Invalid network specification '{network_str}' in rule {i} ('{rule_spec}'): {e}")

                ports_list_or_range = _convert_ports_range(port_spec)
                # _convert_ports_range returns [] for errors or empty valid spec;
                # only raise if original spec was non-empty, non-'*', and resulted in empty.
                if not ports_list_or_range and port_spec.strip() not in ('', '*'):
                    raise ValueError(
                        f"Invalid or empty port specification '{port_spec}' in rule {i} ('{rule_spec}').")

                parsed_rules.append((action, (network, ports_list_or_range), direction))

            setattr(cls, random_rules_name, parsed_rules)
            # Update get_rules to retrieve from the new storage attribute
            setattr(cls, "get_rules", lambda: getattr(cls, random_rules_name))
            logger.info(
                f"Guard_socket rules set successfully with {len(parsed_rules)} rules.")
        else:
            raise ValueError("Rules can only be set once for Guard_socket.")

    get_rules = _get_rules # Class attribute pointing to the rule retrieval function

    def _check_address(self, address: Tuple[str, int], conn_direction: str):
        """
        Internal helper to invoke the rule checking logic.

        Args:
            address: A tuple containing the hostname/IP string and port number.
            conn_direction: The direction of the connection (IN or OUT).
        Raises:
            ValueError: Propagated from _check_address_with_rules.
            RuntimeError: Propagated from _check_address_with_rules.
        """
        rules = Guard_socket.get_rules()
        _check_address_with_rules(rules, address, conn_direction)

    def __init__(self,
                 family: int = socket.AF_INET, # Default to AF_INET if not specified
                 type: int = socket.SOCK_STREAM, # Default to SOCK_STREAM
                 proto: int = 0, # Default protocol
                 fileno: Optional[int] = None):
        """
        Initializes the Guard_socket instance.
        Defaults are similar to standard socket.socket.
        """
        super().__init__(family, type, proto, fileno)

    def bind(self, address: Adresse_Type) -> None:
        """
        Binds the socket to an address.
        For IP-based sockets (AF_INET, AF_INET6), performs rule checking for IN direction.
        AF_UNIX sockets are not subject to IP-based rules and are allowed.
        """
        # Check if address is for AF_INET or AF_INET6 (tuple with host string and port int)
        if isinstance(address, tuple) and len(address) >= 2 and isinstance(address[0], str) and isinstance(address[1], int):
            # Ensure address[0] is a string (hostname or IP) and address[1] is an int (port)
            self._check_address((address[0], address[1]), conn_direction=IN)
        elif isinstance(address, str):  # Likely AF_UNIX
            logger.debug(
                f"Allowing bind to AF_UNIX address (not subject to IP rules): {address}")
            pass # AF_UNIX sockets are not checked by these IP rules
        else:
            # Log a warning for unexpected address formats but allow bind to proceed,
            # as rules are IP-focused.
            logger.warning(
                f"Unexpected address format for bind: {address}. Skipping IP rule check.")
            pass
        super().bind(address)

    def connect(self, address: Adresse_Type) -> None:
        """
        Connects to a remote socket at address.
        For IP-based sockets (AF_INET, AF_INET6), performs rule checking for OUT direction.
        AF_UNIX sockets are not subject to IP-based rules and are allowed.
        """
        if isinstance(address, tuple) and len(address) >= 2 and isinstance(address[0], str) and isinstance(address[1], int):
            self._check_address((address[0], address[1]), conn_direction=OUT)
        elif isinstance(address, str):  # Likely AF_UNIX
            logger.debug(
                f"Allowing connect to AF_UNIX address (not subject to IP rules): {address}")
            pass
        else:
            logger.warning(
                f"Unexpected address format for connect: {address}. Skipping IP rule check.")
            pass
        super().connect(address)

    def connect_ex(self, address: Adresse_Type) -> int:
        """
        Like connect(address), but returns an error indicator instead of raising an exception
        for errors returned by the C-level connect() call (other problems, such as “host not found,”
        can still raise exceptions).
        Performs rule checking for OUT direction before attempting connection for IP-based sockets.
        If rules disallow connection, a RuntimeError is raised.
        """
        try:
            if isinstance(address, tuple) and len(address) >= 2 and isinstance(address[0], str) and isinstance(address[1], int):
                self._check_address((address[0], address[1]), conn_direction=OUT)
            elif isinstance(address, str):  # Likely AF_UNIX
                logger.debug(
                    f"Allowing connect_ex to AF_UNIX address (not subject to IP rules): {address}")
                pass
            else:
                logger.warning(
                    f"Unexpected address format for connect_ex: {address}. Skipping IP rule check.")
                pass
        except RuntimeError as e:
            # If _check_address raises RuntimeError due to rule violation,
            # this should be propagated as it's a guard failure, not a connect_ex style error code.
            logger.error(f"Rule violation during connect_ex pre-check: {e}")
            raise
        return super().connect_ex(address)


# --- Predefined Rule Sets ---
# Rules to deny connections to localhost.
DENY_LOCALHOST: List[Rule] = [
    (DENY, '127.0.0.1:*', OUT),  # Deny IPv4 loopback
    (DENY, '::1:*', OUT)         # Deny IPv6 loopback
]
# Rules to deny connections to common private/intranet IP ranges.
DENY_INTRANET: List[Rule] = [
    (DENY, '10.0.0.0/8:*', OUT),      # Private-Use Networks (RFC 1918)
    (DENY, '169.254.0.0/16:*', OUT),  # Link-Local Addresses (APIPA)
    (DENY, '172.16.0.0/12:*', OUT),   # Private-Use Networks (RFC 1918)
    (DENY, '192.168.0.0/16:*', OUT),  # Private-Use Networks (RFC 1918)
    (DENY, 'fc00::/7:*', OUT)         # Unique Local Addresses (IPv6 RFC 4193)
]
# Rules to deny connections to multicast addresses.
DENY_CAST: List[Rule] = [
    (DENY, '224.0.0.0/4:*', OUT),  # IPv4 Multicast (RFC 5771)
    (DENY, 'ff00::/8:*', OUT),     # IPv6 Multicast (RFC 4291)
]
# Combines DENY_CAST, DENY_LOCALHOST and DENY_INTRANET.
DENY_LOCAL: List[Rule] = DENY_CAST + DENY_LOCALHOST + DENY_INTRANET

# Rules to deny all outgoing internet connections.
DENY_INTERNET: List[Rule] = [
    (ALLOW, '10.0.0.0/8:*', OUT),      # Private-Use Networks (RFC 1918)
    (ALLOW, '169.254.0.0/16:*', OUT),  # Link-Local Addresses (APIPA)
    (ALLOW, '172.16.0.0/12:*', OUT),   # Private-Use Networks (RFC 1918)
    (ALLOW, '192.168.0.0/16:*', OUT),  # Private-Use Networks (RFC 1918)
    (ALLOW, 'fc00::/7:*', OUT)         # Unique Local Addresses (IPv6 RFC 4193)
]
# Rules to allow only standard web ports (HTTP, HTTPS) to any IP.
# Note: This implies a DENY by default if it's the first rule, or needs other DENY rules.
ALLOW_WEB: List[Rule] = [
    (ALLOW, '0.0.0.0/0:80,443', OUT), # Allow IPv4 HTTP/HTTPS
    (ALLOW, '::/0:80,443', OUT),      # Allow IPv6 HTTP/HTTPS
]


# --- Activation & Patching ---
# This block replaces the standard socket.socket with Guard_socket globally
# when this module is imported.
if socket.socket is not Guard_socket:
    socket.socket = Guard_socket
    logger.info("Guard_socket activated. Standard socket.socket has been replaced.")
else:
    # This case would typically not be hit on first import unless the module is reloaded
    # or manipulated in unusual ways.
    logger.info("Guard_socket was already activated.")