# IMPORTANT: This module must be imported *before* any other modules that might
# use the standard `socket` library in your application's main entry point.
#
# Purpose:
# This module patches the standard `socket.socket` class with a custom
# `Guard_socket` class. Its primary role is to intercept and protect network
# socket calls made by Python code using the standard `socket` interface.
#
# Activation:
# The patching happens automatically when this module is imported. To ensure
# that all subsequent uses of `socket.socket` throughout your application
# (including those within third-party libraries) are guarded, this import
# MUST occur before those modules are imported.
#
# Scope of Protection:
# This guard protects against direct socket usage via the Python `socket`
# module. It is designed to mitigate risks from potentially malicious or
# unintended network access originating from Python code, such as code
# generated by an LLM.
#
# Limitations:
# This protection is easily bypassable. It does NOT protect against:
# - Network calls made by native shared libraries (e.g., C/C++ code) invoked
#   by Python.
# - Network calls made by child processes spawned by the Python application.
# - Other forms of inter-process communication.
#
# Nature of Security:
# This is a best-effort security layer within the Python process itself. It
# is NOT a robust security boundary like a firewall, containerization, or
# OS-level sandboxing. It is intended to limit the attack surface specifically
# from potentially untrusted Python code executed within the same process.
#
# Example Usage (in your main application file, e.g., main.py):
# import langgraph_codeagent.sandboxes.guard_socket
# # Now import other modules that use sockets (e.g., requests, urllib, etc.)
# import requests
# import urllib.request
# # ... rest of your application code ...

import ipaddress
import logging
from random import choice
from string import ascii_uppercase
from typing import Tuple, Optional, Union, List, Dict

import socket

logger = logging.getLogger(__name__)

# Address format details can be found in the Python socket library documentation:
# https://docs.python.org/3/library/socket.html#address-families
Adresse_Type = Union[
    str,  # For AF_UNIX sockets
    Tuple[str, int],  # For AF_INET, AF_BLUETOOTH, AF_PACKET, AF_RDS sockets
    Tuple[str, int, int, int],  # For AF_INET6 sockets
    Tuple[int, bytes],  # For AF_NETLINK sockets
    Tuple[str],  # For AF_CAN, PF_SYSTEM sockets
    Tuple[str, str],  # For AF_ALG sockets
    Tuple[int, int],  # For AF_VSOCK, AF_QIPCRTR sockets
    Tuple[int, int, int, int, int]  # For AF_TIPC sockets
]

DENY = "DENY"  # Action to deny a connection
ALLOW = "ALLOW"  # Action to allow a connection
IN = "IN"  # Direction for incoming connections (e.g., server-side bind)
OUT = "OUT"  # Direction for outgoing connections (e.g., client-side connect)

# Rule string format: "--net=ACTION|SOCKET_SPECS|NETWORK_STR|PORT_SPEC_STR|DIRECTION_STR"
# Example: "--net=ALLOW|ipv4,tcp|192.168.1.0/24|80,443|OUT"
# SOCKET_SPECS: comma-separated list of "tcp", "udp", "any".

# Parsed rule format used internally:
# (action_str,
#  (parsed_families: List[int], parsed_types: List[int], network_obj, ports_list_or_range),
#  direction_str)
ParsedRule = Tuple[str,
Tuple[List[int], ipaddress.ip_network, Union[List[int], range]],
str]

SPEC_TO_TYPE_MAP: Dict[str, int] = {
    "tcp": socket.SOCK_STREAM,
    "udp": socket.SOCK_DGRAM,
}


def _parse_rule(i:int, rule:str)-> ParsedRule:
    if not rule.startswith("--net="):
        raise ValueError(
            f"Rule {i} ('{rule}') must start with '--net='.")
    # Remove prefix "--net="
    value_part = rule[len("--net="):]
    # Split by '|' expecting 5 parts: ACTION | SOCKET_SPECS | NETWORK_STR | PORT_SPEC_STR | DIRECTION_STR
    rule_components = value_part.split('|', 4)  # Maxsplit is 4 for 5 parts
    if len(rule_components) != 5:
        raise ValueError(
            f"Rule {i} ('{rule}') has incorrect number of parts separated by '|'. "
            f"Expected 5, got {len(rule_components)}. "
            f"Format: ACTION|SOCKET_SPECS|NETWORK_STR|PORT_SPEC_STR|DIRECTION_STR")
    action, socket_specs_str, network_str, port_spec_str, direction = rule_components
    if action not in (DENY, ALLOW):
        raise ValueError(
            f"Rule {i} action '{action}' is not '{ALLOW}' or '{DENY}'. Rule: {rule}")
    # Parse SOCKET_SPECS
    parsed_rule_families: List[int] = []
    parsed_rule_types: List[int] = []
    specs_input = [s.strip().lower() for s in socket_specs_str.split(',') if
                   s.strip()]
    if not specs_input:
        raise ValueError(f"Rule {i} ('{rule}') has empty SOCKET_SPECS.")
    if "any" in specs_input:
        if len(specs_input) > 1:
            raise ValueError(
                f"Rule {i} ('{rule}'): 'any' in SOCKET_SPECS must be used alone, not combined with other specifiers like '{socket_specs_str}'.")
        # 'any' means parsed_rule_families and parsed_rule_types remain empty (wildcard for both)
    else:
        for spec_part in specs_input:
            if spec_part in SPEC_TO_TYPE_MAP:
                parsed_rule_types.append(SPEC_TO_TYPE_MAP[spec_part])
            else:
                raise ValueError(
                    f"Rule {i} has unknown socket specifier '{spec_part}' in '{socket_specs_str}'. "
                    f"Valid specifiers: 'any', 'ipv4', 'ipv6', 'tcp', 'udp'. Rule: {rule}")

        # Remove duplicates and sort for consistency
        parsed_rule_families = sorted(list(set(parsed_rule_families)))
        parsed_rule_types = sorted(list(set(parsed_rule_types)))
    if not isinstance(network_str, str) or not network_str.strip():
        raise ValueError(
            f"Rule {i} network part '{network_str}' is not a non-empty string. Rule: {rule}")
    if not isinstance(port_spec_str, str):
        raise ValueError(
            f"Rule {i} port spec part '{port_spec_str}' is not a string. Rule: {rule}")
    if direction not in (IN, OUT):
        raise ValueError(
            f"Rule {i} direction '{direction}' is not '{IN}' or '{OUT}'. Rule: {rule}")
    try:
        network = ipaddress.ip_network(network_str, strict=False)
    except ValueError as e:
        raise ValueError(
            f"Invalid network specification '{network_str}' in rule {i} ('{rule}'): {e}")
    ports_list_or_range = _convert_ports_range(port_spec_str)
    if not ports_list_or_range and port_spec_str.strip() not in ('',
                                                                 '*'):
        raise ValueError(
            f"Invalid or empty port specification '{port_spec_str}' in rule {i} ('{rule}') that does not resolve to any ports (and is not '*' or empty string for 'any port' if applicable).")
    return action, (parsed_rule_types, network, ports_list_or_range), direction


def _convert_ports_range(syntaxe: str) -> Union[List[int], range]:
    """
    Converts a port specification string (e.g., "80,443,8000-8080,*")
    into a sorted list of unique integer port numbers or a range object for '*'.

    Args:
        syntaxe: The port specification string.

    Returns:
        A sorted list of integers representing individual ports and expanded ranges,
        or a range(0, 65536) if '*' is specified. Returns an empty list for invalid syntax.
    """
    if not syntaxe:
        return []
    if syntaxe.strip() == '*':
        return range(65536)  # Represents all ports
    ports = set()
    max_port = 65535  # Maximum valid port number
    elements = syntaxe.split(',')
    for element in elements:
        element = element.strip()
        if not element:
            continue
        if '-' in element:
            limites = element.split('-', 1)
            if len(limites) == 2:
                debut_str, end_str = limites[0].strip(), limites[1].strip()
                if not debut_str:
                    raise ValueError(
                        f"Invalid range format: '{element}'. Range start cannot be empty.")
                try:
                    start = int(debut_str)
                except ValueError:
                    raise ValueError(
                        f"Invalid start port number '{debut_str}' in range '{element}'.")
                if not (0 <= start <= max_port):
                    raise ValueError(
                        f"Start port {start} in range '{element}' is out of valid range (0-{max_port}).")

                if end_str == '':  # Handles open-ended ranges like "8000-"
                    end = max_port
                else:
                    try:
                        end = int(end_str)
                    except ValueError:
                        raise ValueError(
                            f"Invalid end port number '{end_str}' in range '{element}'.")
                    if not (0 <= end <= max_port):
                        raise ValueError(
                            f"End port {end} in range '{element}' is out of valid range (0-{max_port}).")
                if start <= end:
                    ports.update(range(start, end + 1))
                else:
                    raise ValueError(
                        f"Invalid range: start port {start} is greater than end port {end} in '{element}'.")
            else:
                raise ValueError(
                    f"Invalid range format: '{element}'. Unexpected hyphen usage.")
        else:
            try:
                port = int(element)
                if not (0 <= port <= max_port):
                    raise ValueError(
                        f"Port number {port} in '{element}' is out of valid range (0-{max_port}).")
                ports.add(port)
            except ValueError:
                raise ValueError(f"Invalid port number '{element}'.")
    return sorted(list(ports))


def _check_address_with_rules(
        rules: List[ParsedRule],
        socket_instance_type: int,
        address: Tuple[str, int],  # Expect (hostname_or_ip_str, port_int)
        conn_direction: str):  # Expect IN or OUT constants
    """
    Checks if a given address and port are allowed for the specified connection direction
    based on the configured rules and the derived implicit default policy.
    (Docstring needs update for new socket_instance_family, socket_instance_proto args)
    """
    logger.debug(
        "_check_address_with_rules(address=%s, conn_direction=%s, type=%s)",
        address, conn_direction, socket_instance_type)
    hostname, destination_port = address

    if not isinstance(destination_port, int) or not (
            0 <= destination_port <= 65535):
        raise ValueError(f"Invalid port number: {destination_port}")

    try:
        # Resolve hostname to IP addresses using the socket instance's family, type, and proto
        infos = socket.getaddrinfo(hostname, None,
                                   type=socket_instance_type)
    except socket.gaierror:
        # Fallback if the specific proto causes issues, try with proto=0 (OS default for family/type)
        # This might happen if self.proto is something specific but getaddrinfo needs a more general hint
        try:
            logger.debug(
                "getaddrinfo failed with specific proto %s, retrying with proto=0")
            infos = socket.getaddrinfo(hostname, None,
                                       type=socket_instance_type, proto=0)
        except socket.gaierror:
            raise ValueError(
                f"Invalid hostname or IP address (resolution failed): {hostname}")

    # %% Analyse ips
    ip_objects = []
    for res_family, _, _, _, sockaddr in infos:
        # sockaddr[0] is the IP address string
        addr_str = sockaddr[0]
        ip_objects.append(ipaddress.ip_address(addr_str))

    unique_ips = list(dict.fromkeys(ip_objects))
    if not unique_ips:
        raise ValueError(
                f"Invalid hostname or IP address (resolution failed): {hostname}")
    if not rules:
        logger.info(
            "Connection to %s port %s ALLOWED because no rules are set.",
            hostname, unique_ips, destination_port
        )
        return

    # %% Analyse rules
    first_rule_action = rules[0][0]
    order_apply = (DENY, ALLOW) if first_rule_action == ALLOW else (ALLOW, DENY)
    implicit_default_is_deny = (first_rule_action == ALLOW)

    logger.debug(
        "First rule is %s, so rule check order is %s, and implicit default for non-matching connections is %s.",
        first_rule_action, order_apply,
        ('DENY' if implicit_default_is_deny else 'ALLOW'))

    for rule_type_to_check in order_apply:
        for ip_host in unique_ips:
            for rule_idx, (action,
                           (rule_types, network_obj, rule_ports_list),
                           rule_direction_from_rule) in enumerate(rules):
                if action == rule_type_to_check:
                    type_match = (not rule_types) or (
                                socket_instance_type in rule_types)

                    if type_match:
                        if rule_direction_from_rule == conn_direction:
                            if ip_host in network_obj and destination_port in rule_ports_list:
                                rule_types_str = [socket.SocketKind(t).name for t in
                                                  rule_types] if rule_types else ["any"]
                                rule_spec_str = f"types={','.join(rule_types_str)}, net={network_obj}, ports={rule_ports_list}, dir={conn_direction}"

                                logger.info(
                                    "Connection to %s (%s:%s) %s by explicit rule #%s: %s (%s)",
                                    hostname, ip_host, destination_port, action,
                                    rule_idx,
                                    action, rule_spec_str
                                )
                                if action == DENY:
                                    raise RuntimeError(
                                        f"Guard network connection to "
                                        f"{ip_host}:{destination_port} (from {hostname}) "
                                        f"explicitly {action} by rule #{rule_idx} "
                                        f"({action} {rule_spec_str})."
                                    )
                                elif action == ALLOW:
                                    raise RuntimeError(
                                        f"Guard network connection to "
                                        f"{ip_host}:{destination_port} (from {hostname}) "
                                        f"explicitly {action} by rule #{rule_idx} "
                                        f"({action} {rule_spec_str})."
                                    )
    if implicit_default_is_deny:
        logger.info(
            "Connection to %s (resolved to %s) port %s DENIED by implicit default policy (first rule was %s, no other rule explicitly matched).",
            hostname, unique_ips, destination_port, first_rule_action
        )
        raise RuntimeError(
            f"Guard network connection to {hostname} (port {destination_port}) "
            f"DENIED by implicit default (first rule: {first_rule_action}). Resolved IPs: {unique_ips}"
        )
    else:
        logger.info(
            "Connection to %s (resolved to %s) port %s ALLOWED by implicit default policy (first rule was %s, no other rule explicitly matched).",
            hostname, unique_ips, destination_port, first_rule_action
        )
        return


_get_rules = lambda: []


class Guard_socket(socket.socket):
    """
    A custom socket class that enforces network rules to restrict connections.
    Rule string format: "--net=ACTION|SOCKET_SPECS|NETWORK_STR|PORT_SPEC_STR|DIRECTION_STR"
    Example: "--net=ALLOW|tcp|192.168.1.0/24|80,443|OUT"
    SOCKET_SPECS: "any", "tcp", "udp", or comma-separated combinations.
    """

    @classmethod
    def set_rules(cls, rules_str_list: List[str]):
        """
        Sets the network rules for the Guard_socket from a list of rule strings.
        Rule string format: "--net=ACTION|SOCKET_SPECS|NETWORK_STR|PORT_SPEC_STR|DIRECTION_STR"
        Example: "--net=ALLOW|ipv4,tcp|192.168.1.0/24|80,443|OUT"

        Args:
            rules_str_list: A list of rule strings.
        Raises:
            ValueError: If rules have already been set or if any rule string is malformed.
        """
        random_rules_name = "_ " + ''.join(choice(ascii_uppercase) for _ in range(12))
        if cls.__dict__.get("get_rules", _get_rules) == _get_rules:
            parsed_rules_list: List[ParsedRule] = []
            for i, rule_str in enumerate(rules_str_list):
                parsed_rule=_parse_rule(i, rule_str)

                parsed_rules_list.append(parsed_rule)

            setattr(cls, random_rules_name, parsed_rules_list)
            setattr(cls, "get_rules", lambda: getattr(cls, random_rules_name))
            logger.info(
                "Guard_socket rules set successfully with %s rules.",
                len(parsed_rules_list))
        else:
            raise ValueError("Rules can only be set once for Guard_socket.")


    get_rules = _get_rules

    def _check_address(self, address: Tuple[str, int], conn_direction: str):
        rules = Guard_socket.get_rules()
        _check_address_with_rules(rules, self.type, self.proto, address,
                                  conn_direction)

    def __init__(self,
                 family: int = socket.AF_INET,
                 type: int = socket.SOCK_STREAM,
                 proto: int = 0,
                 fileno: Optional[int] = None):
        # Ensure family and type are resolved if passed as enum members
        actual_family = family.value if isinstance(family,
                                                   socket.AddressFamily) else family
        actual_type = type.value if isinstance(type, socket.SocketKind) else type

        super().__init__(actual_family, actual_type, proto, fileno)
        # Note: self.family, self.type, self.proto are now available from the superclass

    def bind(self, address: Adresse_Type) -> None:
        if isinstance(address, tuple) and len(address) >= 2 and isinstance(address[0],
                                                                           str) and isinstance(
                address[1], int):
            self._check_address((address[0], address[1]), conn_direction=IN)
        elif isinstance(address, str):  # AF_UNIX
            logger.debug(
                "Allowing bind to AF_UNIX address (not subject to IP rules): %s",
                address)
        else:
            logger.warning(
                "Unexpected address format for bind: %s. Skipping IP rule check.",
                address)
        super().bind(address)

    def connect(self, address: Adresse_Type) -> None:
        if isinstance(address, tuple) and len(address) >= 2 and isinstance(address[0],
                                                                           str) and isinstance(
                address[1], int):
            self._check_address((address[0], address[1]), conn_direction=OUT)
        elif isinstance(address, str):  # AF_UNIX
            logger.debug(
                "Allowing connect to AF_UNIX address (not subject to IP rules): %s",
                address)
        else:
            logger.warning(
                "Unexpected address format for connect: %s. Skipping IP rule check.",
                address)
        super().connect(address)

    def connect_ex(self, address: Adresse_Type) -> int:
        try:
            if isinstance(address, tuple) and len(address) >= 2 and isinstance(
                    address[0], str) and isinstance(address[1], int):
                self._check_address((address[0], address[1]), conn_direction=OUT)
            elif isinstance(address, str):  # AF_UNIX
                logger.debug(
                    "Allowing connect_ex to AF_UNIX address (not subject to IP rules): %s",
                    address)
            else:
                logger.warning(
                    "Unexpected address format for connect_ex: %s. Skipping IP rule check.",
                    address)
        except RuntimeError as e:
            logger.error("Rule violation during connect_ex pre-check: %s", e)
            # Reraise to ensure connect_ex reflects the block, or map to an error code if preferred.
            # For now, reraising the RuntimeError is consistent with connect().
            raise
        return super().connect_ex(address)


# --- Predefined Rule Sets (using new string format) ---
# Rule string format: "--net=ACTION|SOCKET_SPECS|NETWORK_STR|PORT_SPEC_STR|DIRECTION_STR"
# SOCKET_SPECS: "any", "ipv4", "ipv6", "tcp", "udp", or comma-separated combinations.
# e.g., "ipv4,tcp" means AF_INET and SOCK_STREAM
# e.g., "any" means any family, any type.

DENY_LOCALHOST: List[str] = [
    "--net=DENY|any|127.0.0.1|*|OUT",
    "--net=DENY|any|::1|*|OUT"  # For IPv6 localhost
]
DENY_INTRANET: List[str] = [
    "--net=DENY|any|10.0.0.0/8|*|OUT",
    "--net=DENY|any|169.254.0.0/16|*|OUT",  # Link-local
    "--net=DENY|any|172.16.0.0/12|*|OUT",
    "--net=DENY|any|192.168.0.0/16|*|OUT",
    "--net=DENY|any|fc00::/7|*|OUT"  # IPv6 Unique Local Addresses
]
DENY_CAST: List[str] = [
    "--net=DENY|any|224.0.0.0/4|*|OUT",  # IPv4 Multicast
    "--net=DENY|any|ff00::/8|*|OUT",  # IPv6 Multicast
]
DENY_LOCAL: List[str] = DENY_CAST + DENY_LOCALHOST + DENY_INTRANET

# Deny all internet, allow local RFC1918, link-local, unique local.
# If these ALLOW rules are first, implicit default is DENY for everything else.
DENY_INTERNET: List[str] = [
    "--net=ALLOW|any|10.0.0.0/8|*|OUT",
    "--net=ALLOW|any|169.254.0.0/16|*|OUT",
    "--net=ALLOW|any|172.16.0.0/12|*|OUT",
    "--net=ALLOW|any|192.168.0.0/16|*|OUT",
    "--net=ALLOW|any|fc00::/7|*|OUT",
    # To be absolutely explicit about denying all else if these are not the only rules
    # or if the first rule might be a DENY, one could add:
    # "--net=DENY|any|0.0.0.0/0|*|OUT",
    # "--net=DENY|any|::/0|*|OUT" # Corrected from ::0 to ::/0 for all IPv6
    # However, with the current logic, the above ALLOWs imply DENY for others if they are the first rules.
]
ALLOW_WEB: List[str] = [
    "--net=ALLOW|any|0.0.0.0/0|80,443|OUT",  # Allows HTTP/HTTPS to any IPv4
    "--net=ALLOW|any|::/0|80,443|OUT",      # Allows HTTP/HTTPS to any IPv6 (Corrected from ::0)
]

def activate_guard_socket():
    import socket
    # --- Activation & Patching ---
    if socket.socket is not Guard_socket:
        # Ensure that the original socket class is stored if not already.
        # This is important if the module can be reloaded or patched multiple times.
        if not hasattr(socket, '_original_socket_class'):
            socket._original_socket_class = socket.socket  # type: ignore
        socket.socket = Guard_socket
        logger.warning("Guard_socket activated. Standard socket.socket has been replaced.")
    else:
        logger.info("Guard_socket was already activated.")