[project]
name = "mcp-client-demo"
version = "0.1.0"
description = "Sample mcp-client-demo: CLI chatbot using the Model Context Protocol (MCP)"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Philippe PRADOS" }]
keywords = ["sandboxes", "mcp", "llm", "chatbot"]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "pysandboxes",
    "python-dotenv>=1.0",
    "requests>=2.31",
    "mcp>=1.14",
    "uvicorn>=0.32",
    "json-with-comments>=1.2.10",
    "fastmcp>=2.12.4",
    "httpx>=0.28.1",
    "rich>=14.2.0",
]

[dependency-groups]
dev = [
    "ipython",
    "mcp-server-demo",
    "pydevd>=3.4.1",
    "pyright>=1.1.379",
    "ruff>=0.6.9",
#    "pydevd-pycharm>=253.28086.55",
]
test = [
    # The only dependencies that should be added are
    # dependencies used for running tests (e.g., pytest, freezegun, response).
    # Any dependencies that do not meet that criteria will be removed.
    "pytest>=7.3.0",
    "pytest>=8.3.3",
    "pytest-asyncio>=1.2.0",
    "pytest-dotenv>=0.5.2",
    "pytest-asyncio>=0.20.3",
    "pytest-mock>=3.10.0",
]
codespell = [
    "codespell>=2.2.5",
]

[tool.codespell]
skip = '.git,*.pdf,*.svg,*.pdf,*.yaml,*.ipynb,uv.lock,*.min.js,*.css,package-lock.json,./PPR/*'
# Ignore latin etc
ignore-regex = '.*(Stati Uniti|Tense=Pres).*'
#ignore-words-list = ''


[project.scripts]
mcp-simple-chatbot = "mcp_simple_chatbot.main:main"
mcp-simple-chatbot-sb = "mcp_simple_chatbot.main:main_sb"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["mcp_simple_chatbot"]

[tool.pyright]
include = ["mcp_simple_chatbot"]
venvPath = "."
venv = ".venv"

[tool.mypy]
python_version = "3.11"
exclude = [".venv"]
ignore_missing_imports = true
explicit_package_bases = true
namespace_packages = true

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.uv]

[tool.uv.sources]
# Use only inside the pysandboxes git repository
pysandboxes = { path = "../..", editable = true }
mcp-server-demo = { path = "../mcp-server-demo", editable = true }

[tool.pytest.ini_options]
# --strict-markers will raise errors on unknown marks.
# https://docs.pytest.org/en/7.1.x/how-to/mark.html#raising-errors-on-unknown-marks
#
# https://docs.pytest.org/en/7.1.x/reference/reference.html
# --strict-config       any warnings encountered while parsing the `pytest`
#                       section of the configuration file raise errors.
#
# https://github.com/tophat/syrupy
addopts = "--strict-markers --strict-config -vv"
#asyncio_mode = "auto"
