apiVersion: v1
kind: Pod
metadata:
  name: pysandboxes-test
spec:
  containers:
    - name: pysandboxes-test
      image: pysandboxes:latest
      imagePullPolicy: Never   # Image construite localement dans minikube (eval $(minikube docker-env) + docker build)
      workingDir: /app
      command: [ "/bin/sh", "-c","sleep infinity" ] # Garde le pod en vie
      securityContext:
        privileged: true   # Requis pour mount /proc dans le namespace unshare (sandbox)
        capabilities:
          add:
            - SYS_ADMIN   # Permet unshare (créer des namespaces)
            - NET_ADMIN   # Permet la configuration réseau (ip link, etc.)
        seccompProfile:
          type: Unconfined  # Désactive le filtre qui bloque unshare
      volumeMounts:
        - name: code-local
          mountPath: /app  # Chemin à l'intérieur du Pod
        - name: dev-net-tun
          mountPath: /dev/net/tun  # Requis par slirp4netns
  volumes:
    - name: code-local
      hostPath:
        path: /mnt/pysandboxes
        type: Directory
    - name: dev-net-tun
      hostPath:
        path: /dev/net/tun
        type: CharDevice
