apiVersion: v1
kind: Pod
metadata:
  name: pysandboxes-test
spec:
  containers:
    - name: pysandboxes-test
      image: python:latest
      workingDir: /app
      command: [ "/bin/sh", "-c","sleep infinity" ] # Garde le pod en vie
      securityContext:
        capabilities:
          add:
            - SYS_ADMIN   # Permet unshare (créer des namespaces)
            - NET_ADMIN    # Permet la configuration réseau (ip link, etc.)
        seccompProfile:
          type: Unconfined  # Désactive le filtre qui bloque unshare
#      command: [ "/bin/sh", "-c" ] # Garde le pod en vie
#      args:
#        - |
#          apt update && \
#          apt install -y libvirt-dev pkg-config iptables iproute2 slirp4netns && \
#          pip install -e . && \
#          OS_SANDBOX=unshare python-sb -m tests.integration_tests.tst_usage
      volumeMounts:
        - name: code-local
          mountPath: /app  # Chemin à l'intérieur du Pod
        - name: dev-net-tun
          mountPath: /dev/net/tun  # Requis par slirp4netns
  volumes:
    - name: code-local
      hostPath:
        path: /mnt/pysandboxes
        type: Directory
    - name: dev-net-tun
      hostPath:
        path: /dev/net/tun
        type: CharDevice
