# IMPORTANT: This module must be imported *before* any other modules that might
# use the standard `socket` library in your application's main entry point.
#
# Purpose:
# This module patches the standard `socket.socket` class with a custom
# `Guard_socket` class. Its primary role is to intercept and protect network
# socket calls made by Python code using the standard `socket` interface.
#
# Activation:
# The patching happens automatically when this module is imported. To ensure
# that all subsequent uses of `socket.socket` throughout your application
# (including those within third-party libraries) are guarded, this import
# MUST occur before those modules are imported.
#
# Scope of Protection:
# This guard protects against direct socket usage via the Python `socket`
# module. It is designed to mitigate risks from potentially malicious or
# unintended network access originating from Python code, such as code
# generated by an LLM.
#
# Limitations:
# This protection is easily bypassable. It does NOT protect against:
# - Network calls made by native shared libraries (e.g., C/C++ code) invoked
#   by Python.
# - Network calls made by child processes spawned by the Python application.
# - Other forms of inter-process communication.
#
# Nature of Security:
# This is a best-effort security layer within the Python process itself. It
# is NOT a robust security boundary like a firewall, containerization, or
# OS-level sandboxing. It is intended to limit the attack surface specifically
# from potentially untrusted Python code executed within the same process.
#
# Example Usage (in your main application file, e.g., main.py):
# import langgraph_codeagent.sandboxes.guard_socket
# # Now import other modules that use sockets (e.g., requests, urllib, etc.)
# import requests
# import urllib.request
# # ... rest of your application code ...
import ipaddress
import logging
import os
import socket
import sys
from ipaddress import IPv4Network, IPv6Network
from pathlib import Path
from typing import Tuple, Optional, Union, List, Dict, NamedTuple, cast, Any

from .exception import RuleError
from .main_logger import format_ruleref, ErrorMsg, pysandboxes_logger
from .types import ConfigLines, ConfigLine

logger = logging.getLogger(__name__)


# Parsed rule format used internally:
class SocketMask(NamedTuple):
    families: List[str]
    types: List[int]
    network: Union[IPv4Network, IPv6Network]
    ports: Union[List[int], range]


class SocketRule(NamedTuple):
    action: str
    mask: SocketMask
    direction: str
    config: ConfigLine


SocketRules = Tuple[SocketRule, ...]


class SocketRulesError(RuleError):  # TODO: Se brancher sur une exception classique ?
    pass


# Address format details can be found in the Python socket library documentation:
# https://docs.python.org/3/library/socket.html#address-families
Adresse_Type = Union[
    str,  # For AF_UNIX sockets
    Tuple[str, int],  # For AF_INET, AF_BLUETOOTH, AF_PACKET, AF_RDS sockets
    Tuple[str, int, int, int],  # For AF_INET6 sockets
    Tuple[int, bytes],  # For AF_NETLINK sockets
    Tuple[str],  # For AF_CAN, PF_SYSTEM sockets
    Tuple[str, str],  # For AF_ALG sockets
    Tuple[int, int],  # For AF_VSOCK, AF_QIPCRTR sockets
    Tuple[int, int, int, int, int]  # For AF_TIPC sockets
]

DENY = "DENY"  # Action to deny a connection
ALLOW = "ALLOW"  # Action to allow a connection
IN = "IN"  # Direction for incoming connections (e.g., server-side bind)
OUT = "OUT"  # Direction for outgoing connections (e.g., client-side connect)

# Rule string format: "--net=ACTION|SOCKET_SPECS|NETWORK_STR|PORT_SPEC_STR|DIRECTION_STR"
# Example: "--net=ALLOW|ipv4,tcp|192.168.1.0/24|80,443|OUT"
# SOCKET_SPECS: comma-separated list of "tcp", "udp", "any".


_rules: SocketRules = cast(SocketRules, ())

SPEC_TO_TYPE_MAP: Dict[str, int] = {
    "tcp": socket.IPPROTO_TCP,
    "udp": socket.IPPROTO_UDP,
    # "icmp": socket.IPPROTO_ICMP,
    # "icmpv6": socket.IPPROTO_ICMPV6,
    # "any": -1,
    # "*": -1,
}


def _parse_rule(rule: ConfigLine,
                errors: List[Tuple[str, Path, int]]) -> Optional[List[SocketRule]]:
    if not rule.rule.startswith("--net="):
        return []
    value_part = rule.rule[len("--net="):]
    rule_components = value_part.split('|', 4)  # Maxsplit is 4 for 5 parts
    if len(rule_components) != 5:
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"'{rule.rule}' has incorrect number of parts separated by '|'. "
                f"Expected 5, got {len(rule_components)}. "
                f"Format: "
                f"<{ALLOW}, {DENY}>|"
                f"<{','.join(SPEC_TO_TYPE_MAP)} list or any>|"
                f"<ip/mask>, *|"
                f"<port list>|"
                f"<IN, OUT>.",
                rule.path,
                rule.ln
            )
        )
        return None
    action, socket_specs_str, network_str, port_spec_str, direction = rule_components
    if action not in (DENY, ALLOW):
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"'{rule.rule}' "
                f"use an invalide action. Must be '{ALLOW}' or '{DENY}'.",
                rule.path,
                rule.ln
            )
        )
        return None

    # Parse SOCKET_SPECS
    parsed_rule_types: List[int] = []
    specs_input = [s.strip().lower() for s in socket_specs_str.split(',') if
                   s.strip()]
    if not specs_input:
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"'{rule.rule}' "
                f"has empty socket specs.",
                rule.path,
                rule.ln
            )
        )
        return None
    else:
        for spec_part in specs_input:
            if spec_part in ["any", "*"]:
                if len(specs_input) > 1:
                    errors.append(
                        (
                            f"{format_ruleref(rule)}: "
                            f"In '{rule.rule}', "
                            f"'{spec_part}' must be used alone, "
                            f"not combined with other specifiers.",
                            rule.path,
                            rule.ln
                        )
                    )
                    return []
                parsed_rule_types = []

            elif spec_part in SPEC_TO_TYPE_MAP:
                parsed_rule_types.append(SPEC_TO_TYPE_MAP[spec_part])
            else:
                errors.append(
                    (
                        f"{format_ruleref(rule)}: "
                        f"'{rule.rule}' "
                        f"has unknown socket specifier '{spec_part}'."
                        f"Valid specifiers: any, {', '.join(SPEC_TO_TYPE_MAP.keys())}.",
                        rule.path,
                        rule.ln
                    )
                )
                return None

        parsed_rule_types = sorted(list(set(parsed_rule_types)))
    if not isinstance(network_str, str) or not network_str.strip():
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"In '{rule.rule}', "
                f"network part must be set.",
                rule.path,
                rule.ln
            )
        )
        return None
    if not isinstance(port_spec_str, str):
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"In '{rule.rule}', "
                f"port spec part is not valid.",
                rule.path,
                rule.ln
            )
        )
        return None
    if direction not in (IN, OUT):
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"In '{rule.rule}', "
                f"direction is not '{IN}' or '{OUT}'.",
                rule.path,
                rule.ln
            )
        )
        return None
    try:
        ports_list_or_range = _convert_ports_range(port_spec_str)
    except ValueError as e:
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"In '{rule.rule}', "
                f"invalide port list.",
                rule.path,
                rule.ln
            )
        )
        return None
    if network_str in ("*",):
        network_str = "0.0.0.0/0"

    def _for_each_networks(network: Union[IPv4Network, IPv6Network]):
        return SocketRule(action,
                          SocketMask(
                              specs_input,
                              parsed_rule_types,
                              # May not be resolved
                              network,
                              ports_list_or_range),
                          direction,
                          config=rule)

    try:
        return [
            _for_each_networks(ipaddress.ip_network(network_str, strict=False))
        ]
    except ValueError as e:
        try:
            _, _, networks = socket.gethostbyname_ex(network_str)
            return [_for_each_networks(ipaddress.ip_network(network, strict=False)) for
                    network in networks]
        except socket.gaierror as e:
            errors.append(
                (
                    f"{format_ruleref(rule)}: "
                    f"In '{rule.rule}', "
                    f"invalid network specification."
                    f"That does not resolve to any network.",
                    rule.path,
                    rule.ln
                )
            )
            return None


def parse_rules(rules: ConfigLines,
                errors: List[ErrorMsg]
                ) -> Tuple[SocketRules, ConfigLines]:
    socket_rules = []
    ignore_rules = []
    for rule in rules:
        parsed_rules = _parse_rule(rule, errors)
        if parsed_rules:
            socket_rules.extend(parsed_rules)
        elif parsed_rules is not None:
            ignore_rules.append(rule)

    # TODO: Remove duplicates and sort for consistency
    # parsed_rule_families = sorted(list(set(parsed_rule_families)))  # FIXME

    return tuple(socket_rules), ignore_rules

def generate_rules(
        learn: List[Any],
                ) -> List[str]:
    return []


def _convert_ports_range(syntax: str) -> Union[List[int], range]:
    """
    Converts a port specification string (e.g., "80,443,8000-8080,*")
    into a sorted list of unique integer port numbers or a range object for '*'.

    Args:
        syntax: The port specification string.

    Returns:
        A sorted list of integers representing individual ports and expanded ranges,
        or a range(0, 65535) if '*' is specified. Returns an empty list for invalid syntax.
    """
    max_port = 65535  # Maximum valid port number
    if not syntax:
        return []
    if syntax.strip() == '*':
        return range(max_port + 1)  # Represents all ports
    ports = set()
    elements = syntax.split(',')
    for element in elements:
        element = element.strip()
        if not element:
            continue
        if '-' in element:
            limits = element.split('-', 1)
            if len(limits) == 2:
                start_str, end_str = limits[0].strip(), limits[1].strip()
                if not start_str:
                    raise ValueError(
                        f"Invalid range format: '{element}'. Range start cannot be empty.")
                try:
                    start = int(start_str)
                except ValueError:
                    raise ValueError(
                        f"Invalid start port number '{start_str}' in range '{element}'.")
                if not (0 <= start <= max_port):
                    raise ValueError(
                        f"Start port {start} in range '{element}' is out of valid range (0-{max_port}).")

                if end_str == '':  # Handles open-ended ranges like "8000-"
                    end = max_port
                else:
                    try:
                        end = int(end_str)
                    except ValueError:
                        raise ValueError(
                            f"Invalid end port number '{end_str}' in range '{element}'.")
                    if not (0 <= end <= max_port):
                        raise ValueError(
                            f"End port {end} in range '{element}' is out of valid range (0-{max_port}).")
                if start == end:
                    ports.add(start)
                elif start <= end:
                    ports.add(range(start, end + 1))
                else:
                    raise ValueError(
                        f"Invalid range: start port {start} is greater than end port {end} in '{element}'.")
            else:
                raise ValueError(
                    f"Invalid range format: '{element}'. Unexpected hyphen usage.")
        else:
            try:
                port = int(element)
                if not (0 <= port <= max_port):
                    raise ValueError(
                        f"Port number {port} in '{element}' is out of valid range (0-{max_port}).")
                ports.add(port)
            except ValueError:
                raise ValueError(f"Invalid port number '{element}'.")
    if len(ports) == 1:
        first = next(iter(ports))
        if isinstance(first, range):
            return first
    list_port = set()
    for port in ports:
        if isinstance(port, range):
            list_port.update(list(port))
        else:
            list_port.add(port)
    return sorted(list_port)


def _check_address_with_rules(
        socket_rules: SocketRules,
        socket_instance_type: int,
        address: Tuple[str, int],  # Expect (hostname_or_ip_str, port_int)
        conn_direction: str):  # Expect IN or OUT constants
    """
    Checks if a given address and port are allowed for the specified connection direction
    based on the configured socket_rules and the derived implicit default policy.
    (Docstring needs update for new socket_instance_family, socket_instance_proto args)
    """
    logger.debug(
        "_check_address_with_rules(address=%s, conn_direction=%s, type=%s)",
        address, conn_direction, socket_instance_type)
    hostname, destination_port = address

    if not isinstance(destination_port, int) or not (
            0 <= destination_port <= 65535):
        raise ValueError(f"Invalid port number: {destination_port}")

    try:
        # Resolve hostname to IP addresses using the socket instance's family, type, and proto
        infos = socket.getaddrinfo(hostname, None,
                                   type=socket_instance_type)
    except socket.gaierror:
        # Fallback if the specific proto causes issues, try with proto=0 (OS default for family/type)
        # This might happen if self.proto is something specific but getaddrinfo needs a more general hint
        try:
            logger.debug(
                "getaddrinfo failed with specific proto %s, retrying with proto=0")
            infos = socket.getaddrinfo(hostname, None,
                                       type=socket_instance_type, proto=0)
        except socket.gaierror:
            raise ValueError(
                f"Invalid hostname or IP address (resolution failed): {hostname}")

    # %% Analyse ips
    ip_objects = []
    for res_family, _, _, _, sockaddr in infos:
        # sockaddr[0] is the IP address string
        addr_str = sockaddr[0]
        ip_objects.append(ipaddress.ip_address(addr_str))

    unique_ips = list(dict.fromkeys(ip_objects))
    if not unique_ips:
        raise ValueError(
            f"Invalid hostname or IP address (resolution failed): {hostname}")
    # if not socket_rules:  # FIXME: remove
    #     logger.info(
    #         "Connection to %s port %s ALLOWED because no socket_rules are set.",
    #         hostname, destination_port
    #     )
    #     return

    # %% Analyse socket_rules
    order_apply = (DENY, ALLOW)

    for rule_type_to_check in (DENY, ALLOW):
        for ip_host in unique_ips:
            for (action,
                 (rule_families, rule_types, network_obj, rule_ports_list),
                 rule_direction_from_rule,
                 config) in socket_rules:
                if action == rule_type_to_check:
                    type_match = (not rule_types) or (
                            socket_instance_type in rule_types)

                    if type_match:
                        if rule_direction_from_rule == conn_direction:
                            if ip_host in network_obj and destination_port in rule_ports_list:

                                pysandboxes_logger.info(
                                    "Connection to '%s' (%s:%s) %s by explicit "
                                    "rule '%s' from %s",
                                    hostname, ip_host, destination_port, action,
                                    config.rule, format_ruleref(config)
                                )
                                if action == DENY:
                                    raise SocketRulesError(
                                        f"Guard network connection to "
                                        f"'{hostname}' ({ip_host}:{destination_port}) "
                                        f"{action} by rule "
                                        f"'{config.rule}' "
                                        f"from {format_ruleref(config)})."
                                    )
                                elif action == ALLOW:
                                    raise SocketRulesError(
                                        f"Guard network connection to "
                                        f"'{hostname}' ({ip_host}:{destination_port}) "
                                        f"{action} by rule "
                                        f"'{config.rule}' from {format_ruleref(config)})."
                                    )
    pysandboxes_logger.info(
        "Connection to '%s' (%s:%s) "
        "DENIED by implicit default policy.",
        hostname, unique_ips, destination_port
    )
    raise SocketRulesError(
        f"Guard network connection to '{hostname}' "
        f"({unique_ips}:{destination_port}) "
        f"DENIED by implicit default policy."
    )


_get_rules = lambda: []


class Guard_socket(socket.socket):
    """
    A custom socket class that enforces network socket_rules to restrict connections.
    Rule string format: "--net=ACTION|SOCKET_SPECS|NETWORK_STR|PORT_SPEC_STR|DIRECTION_STR"
    Example: "--net=ALLOW|tcp|192.168.1.0/24|80,443|OUT"
    SOCKET_SPECS: "any", "tcp", "udp", or comma-separated combinations.
    """

    def _check_address(self, address: Tuple[str, int], conn_direction: str):
        rules = Guard_socket.get_rules()
        _check_address_with_rules(rules, self.type, self.proto, address,
                                  conn_direction)

    def __init__(self,
                 family: int = socket.AF_INET,
                 type: int = socket.SOCK_STREAM,
                 proto: int = 0,
                 fileno: Optional[int] = None):
        # Ensure family and type are resolved if passed as enum members
        actual_family = family.value if isinstance(family,
                                                   socket.AddressFamily) else family
        actual_type = type.value if isinstance(type, socket.SocketKind) else type

        super().__init__(actual_family, actual_type, proto, fileno)
        # Note: self.family, self.type, self.proto are now available from the superclass

    def bind(self, address: Adresse_Type) -> None:
        if (isinstance(address, tuple) and len(address) >= 2 and  # FIXME: ajout de test
                isinstance(address[0], str)
                and isinstance(address[1], int)):
            self._check_address((str(address[0]), int(address[1])), conn_direction=IN)
        elif isinstance(address, str):  # AF_UNIX
            logger.debug(
                "Allowing bind to AF_UNIX address (not subject to IP socket_rules): %s",
                address)
        else:
            logger.warning(
                "Unexpected address format for bind: %s. Skipping IP rule check.",
                address)
        super().bind(address)

    def connect(self, address: Adresse_Type) -> None:
        if (isinstance(address, tuple) and len(address) >= 2
                and isinstance(address[0], str)
                and isinstance(address[1], int)):
            self._check_address((str(address[0]), int(address[1])), conn_direction=OUT)
        elif isinstance(address, str):  # AF_UNIX
            logger.debug(
                "Allowing connect to AF_UNIX address (not subject to IP socket_rules): %s",
                address)
        else:
            logger.warning(
                "Unexpected address format for connect: %s. Skipping IP rule check.",
                address)
        super().connect(address)

    def connect_ex(self, address: Adresse_Type) -> int:
        try:
            if isinstance(address, tuple) and len(address) >= 2 and isinstance(
                    address[0], str) and isinstance(address[1], int):
                self._check_address((address[0], address[1]), conn_direction=OUT)
            elif isinstance(address, str):  # AF_UNIX
                logger.debug(
                    "Allowing connect_ex to AF_UNIX address (not subject to IP socket_rules): %s",
                    address)
            else:
                logger.warning(
                    "Unexpected address format for connect_ex: %s. Skipping IP rule check.",
                    address)
        except SocketRulesError as e:
            logger.error("Rule violation during connect_ex pre-check: %s", e)
            # Reraise to ensure connect_ex reflects the block, or map to an error code if preferred.
            # For now, reraising the SocketRulesError is consistent with connect().
            raise
        return super().connect_ex(address)


# %%
if "PYTEST_RUN_CONFIG" in os.environ:
    from unit_tests import save_default_values, restore_default_values

    _key_to_remember = {
        "socket.socket",
    }
    _memory = dict()
    save_default_values(_memory,
                        _key_to_remember,
                        sys.modules[__name__],
                        )


    def _deactivate_guard_sockets():
        restore_default_values(_memory,
                               sys.modules[__name__])
        global _rules
        _rules = []


def activate_guard_socket(socket_rules: SocketRules) -> None:
    if not socket_rules:
        return
    global _rules
    if _rules:
        raise RuntimeError("Guard_socket already activated.")
    _rules = socket_rules
    install_wrapper = not _rules

    if install_wrapper:
        import socket
        # --- Activation & Patching ---
        if socket.socket is not Guard_socket:
            # Ensure that the original socket class is stored if not already.
            # This is important if the module can be reloaded or patched multiple times.
            if not hasattr(socket, '_original_socket_class'):
                socket._original_socket_class = socket.socket  # type: ignore
            socket.socket = Guard_socket
        pysandboxes_logger.warning(
            "Guard_socket activated.")
