# IMPORTANT: This module must be imported *before* any other modules that might
# use the standard `socket` library in your application's main entry point.
#
# Purpose:
# This module patches the standard `socket.socket` class with a custom
# `Guard_socket` class. Its primary role is to intercept and protect network
# socket calls made by Python code using the standard `socket` interface.
#
# Activation:
# The patching happens automatically when this module is imported. To ensure
# that all subsequent uses of `socket.socket` throughout your application
# (including those within third-party libraries) are guarded, this import
# MUST occur before those modules are imported.
#
# Scope of Protection:
# This guard protects against direct socket usage via the Python `socket`
# module. It is designed to mitigate risks from potentially malicious or
# unintended network access originating from Python code, such as code
# generated by an LLM.
#
# Limitations:
# This protection is easily bypassable. It does NOT protect against:
# - Network calls made by native shared libraries (e.g., C/C++ code) invoked
#   by Python.
# - Network calls made by child processes spawned by the Python application.
# - Other forms of inter-process communication.
#
# Nature of Security:
# This is a best-effort security layer within the Python process itself. It
# is NOT a robust security boundary like a firewall, containerization, or
# OS-level sandboxing. It is intended to limit the attack surface specifically
# from potentially untrusted Python code executed within the same process.
#
# Example Usage (in your main application file, e.g., main.py):
# import langgraph_codeagent.sandboxes.guard_socket
# # Now import other modules that use sockets (e.g., requests, urllib, etc.)
# import requests
# import urllib.request
# # ... rest of your application code ...
import functools
import logging
import os
import socket
import sys
from collections.abc import Buffer
from enum import IntEnum, Enum
from ipaddress import IPv4Network, IPv6Network, ip_network, IPv4Address, IPv6Address, \
    ip_address
from pathlib import Path
from typing import Tuple, Optional, Union, List, Dict, NamedTuple, cast, Any, Callable, \
    TypeAlias, Set, Generator

from .e import RuleSocketConnectionRefusedError
from .learning import is_learning_mode, add_learning_rule
from .main_logger import format_ruleref, ErrorMsg, pysandboxes_logger
from .sb_types import ConfigLines, ConfigLine

logger = logging.getLogger(__name__)

# Address format details can be found in the Python socket library documentation:
# https://docs.python.org/3/library/socket.html#address-families
Adresse_Type = Union[
    str,  # For AF_UNIX sockets
    Tuple[str, int],  # For AF_INET, AF_BLUETOOTH, AF_PACKET, AF_RDS sockets
    Tuple[str, int, int, int],  # For AF_INET6 sockets
    Tuple[int, bytes],  # For AF_NETLINK sockets
    Tuple[str],  # For AF_CAN, PF_SYSTEM sockets
    Tuple[str, str],  # For AF_ALG sockets
    Tuple[int, int],  # For AF_VSOCK, AF_QIPCRTR sockets
    Tuple[int, int, int, int, int]  # For AF_TIPC sockets
]


class Action(IntEnum):
    DENY = 1  # Action to deny a connection
    ALLOW = 0  # Action to allow a connection


class Direction(IntEnum):
    OUT = 1  # Direction for outgoing connections (e.g., client-side connect)
    IN = 0  # Direction for incoming connections (e.g., server-side bind)


class Kind(Enum):
    TCP = socket.SOCK_STREAM
    UDP = socket.SOCK_DGRAM
    UNKNOWN = socket.SOCK_DGRAM


# Parsed rule format used internally:
class SocketMask(NamedTuple):
    kinds: Tuple[Kind, ...]
    network: Union[IPv4Network, IPv6Network]
    ports: Union[Tuple[int, ...], range]


class SocketRule(NamedTuple):
    action: Action
    mask: SocketMask
    directions: Tuple[Direction, ...]
    config: ConfigLine


SocketRules = Tuple[SocketRule, ...]


class LearnSocketRule(NamedTuple):
    fn: str
    kind: Kind
    address: str
    port: int
    direction: Optional[Direction]
    dns: Tuple[Union[IPv4Address, IPv6Address], ...]


_all_networks = ["0.0.0.0/0", "::1/0"]

# Rule string format: "net=ACTION|SOCKET_SPECS|NETWORK_STR|PORT_SPEC_STR|DIRECTION_STR"
# Example: "net=ALLOW|ipv4,tcp|192.168.1.0/24|80,443|OUT"
# SOCKET_SPECS: comma-separated list of "tcp", "udp", "any".


_rules: SocketRules = cast(SocketRules, ())


def _yield_networks_from_string(input_str: str) -> Generator[
    Union[IPv4Network, IPv6Network], None, None]:
    host_dns, _ = _read_host_file()
    try:
        # Case 1: The input is a network in CIDR notation (e.g., '192.168.1.0/24')
        network = ip_network(input_str, strict=False)
        yield network
        # for subnet in network.subnets():
        #     yield subnet
    except ValueError:
        # Case 2: The input is a hostname (e.g., 'www.google.com')
        # Resolve all IPs for the hostname and treat each as a /32 or /128 network
        if input_str in host_dns:
            yield ip_network(host_dns[input_str],strict=False)
        else:
            addresses = socket.gethostbyname_ex(input_str)[2]
            for ip_address_str in addresses:
                ip = ip_address(ip_address_str)
                yield ip_network(ip)


def _parse_rule(rule: ConfigLine,
                errors: List[Tuple[str, Path, int]]) -> Optional[List[SocketRule]]:
    if not rule.rule.startswith("net="):
        return []
    value_part = rule.rule[len("net="):]
    rule_components = value_part.split('|', 4)  # Maxsplit is 4 for 5 parts
    if len(rule_components) != 5:
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"{rule.rule!r} has incorrect number of parts separated by '|'. "
                f"Expected 5, got {len(rule_components)}. "
                f"Format: "
                f"<{','.join(Action)}>|"
                f"<{','.join([k.name for k in Kind])} list or *>|"
                f"<ip/mask>, *|"
                f"<port list>|"
                f"<IN, OUT>.",
                rule.path,
                rule.ln
            )
        )
    action, socket_specs_str, network_str, port_spec_str, directions = rule_components
    if action not in (Action.DENY.name, Action.ALLOW.name):
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"{rule.rule!r} "
                f"use an invalide action. Must be {Action.ALLOW.name!r} "
                f"or {Action.DENY.name!r}.",
                rule.path,
                rule.ln
            )
        )

    # Parse SOCKET_SPECS
    parsed_rule_kinds: List[Kind] = []
    kind_input = [s.strip().lower() for s in socket_specs_str.split(',') if
                  s.strip()]
    if not kind_input:
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"{rule.rule!r} "
                f"has empty socket specs.",
                rule.path,
                rule.ln
            )
        )
    else:
        for spec_part in kind_input:
            spec_part = spec_part.upper()
            if spec_part in ["ANY", "*"]:
                if len(kind_input) > 1:
                    errors.append(
                        (
                            f"{format_ruleref(rule)}: "
                            f"In {rule.rule!r}, "
                            f"{spec_part!r} must be used alone, "
                            f"not combined with other specifiers.",
                            rule.path,
                            rule.ln
                        )
                    )
                else:
                    parsed_rule_kinds = list(Kind)

            elif spec_part in [k.name for k in Kind]:
                parsed_rule_kinds.append(Kind[spec_part])
            else:
                errors.append(
                    (
                        f"{format_ruleref(rule)}: "
                        f"{rule.rule!r} "
                        f"has unknown socket specifier {spec_part!r}. "
                        f"Valid specifiers: any, {', '.join([k.name for k in Kind])}.",
                        rule.path,
                        rule.ln
                    )
                )

    if not isinstance(network_str, str) or not network_str.strip():
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"In {rule.rule!r}, "
                f"network part must be set.",
                rule.path,
                rule.ln
            )
        )
    if not isinstance(port_spec_str, str):
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"In {rule.rule!r}, "
                f"port spec part is not valid.",
                rule.path,
                rule.ln
            )
        )
    split_directions = directions.split(',')
    if not set(split_directions).issubset({Direction.IN.name, Direction.OUT.name, "*"}):
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"In {rule.rule!r}, "
                f"direction is not {Direction.IN.name!r} "
                f"or {Direction.OUT.name!r}.",
                rule.path,
                rule.ln
            )
        )
    if "*" in split_directions:
        parser_directions = tuple(Direction)
    else:
        parser_directions = tuple([Direction[d] for d in split_directions])

    try:
        ports_list_or_range = _convert_ports_range(port_spec_str)
    except ValueError:
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"In {rule.rule!r}, "
                f"invalide port list.",
                rule.path,
                rule.ln
            )
        )
    if network_str in ("*",):
        networks = _all_networks
    else:
        networks = [network_str]

    if errors:
        return None

    def _for_each_networks():
        for network in networks:
            for network in _yield_networks_from_string(network):
                yield SocketRule(Action[action],
                                 SocketMask(
                                     tuple(parsed_rule_kinds),
                                     # May not be resolved
                                     network,
                                     ports_list_or_range),
                                 parser_directions,
                                 config=rule)

    try:
        r = list(_for_each_networks())
        return r
    except socket.gaierror:
        errors.append(
            (
                f"{format_ruleref(rule)}: "
                f"In {rule.rule!r}, "
                f"invalid network specification. "
                f"That does not resolve to any network.",
                rule.path,
                rule.ln
            )
        )
        return None


def parse_rules(rules: ConfigLines,
                errors: List[ErrorMsg]
                ) -> Tuple[SocketRules, ConfigLines]:
    socket_rules = []
    ignore_rules = []
    for rule in rules:
        parsed_rules = _parse_rule(rule, errors)
        if parsed_rules:
            socket_rules.extend(parsed_rules)
        elif parsed_rules is not None:
            ignore_rules.append(rule)

    # Remove duplicates and sort for consistency
    sorted_rules = sorted(set(socket_rules),
                          key=lambda rule: (rule.action,
                                            len(rule.mask.kinds),
                                            len(rule.mask.ports),
                                            len(rule.directions)
                                            ), reverse=True)
    return tuple(sorted_rules), ignore_rules


def _convert_ports_range(syntax: str) -> Union[Tuple[int, ...], range]:
    """
    Converts a port specification string (e.g., "80,443,8000-8080,*")
    into a sorted list of unique integer port numbers or a range object for '*'.

    Args:
        syntax: The port specification string.

    Returns:
        A sorted list of integers representing individual ports and expanded ranges,
        or a range(0, 65535) if '*' is specified. Returns an empty list for invalid syntax.
    """
    max_port = 65535  # Maximum valid port number
    if not syntax:
        return tuple()
    if syntax.strip() == '*':
        return range(max_port + 1)  # Represents all ports
    ports = set()
    elements = syntax.split(',')
    for element in elements:
        element = element.strip()
        if not element:
            continue
        if '-' in element:
            limits = element.split('-', 1)
            if len(limits) == 2:
                start_str, end_str = limits[0].strip(), limits[1].strip()
                if not start_str:
                    raise ValueError(
                        f"Invalid range format: {element!r}. Range start cannot be empty.")
                try:
                    start = int(start_str)
                except ValueError:
                    raise ValueError(
                        f"Invalid start port number {start_str!r} in range {element!r}.")
                if not (0 <= start <= max_port):
                    raise ValueError(
                        f"Start port {start} in range {element!r} is out of valid range (0-{max_port}).")

                if end_str == '':  # Handles open-ended ranges like "8000-"
                    end = max_port
                else:
                    try:
                        end = int(end_str)
                    except ValueError:
                        raise ValueError(
                            f"Invalid end port number {end_str!r} in range {element!r}.")
                    if not (0 <= end <= max_port):
                        raise ValueError(
                            f"End port {end} in range {element!r} is out of valid range (0-{max_port}).")
                if start == end:
                    ports.add(start)
                elif start <= end:
                    ports.add(range(start, end + 1))
                else:
                    raise ValueError(
                        f"Invalid range: start port {start} is greater than end port {end} in {element!r}.")
            else:
                raise ValueError(
                    f"Invalid range format: {element!r}. Unexpected hyphen usage.")
        else:
            try:
                port = int(element)
                if not (0 <= port <= max_port):
                    raise ValueError(
                        f"Port number {port} in {element!r} is out of valid range (0-{max_port}).")
                ports.add(port)
            except ValueError:
                raise ValueError(f"Invalid port number {element!r}.")
    if len(ports) == 1:
        first = next(iter(ports))
        if isinstance(first, range):
            return first
    list_port = set()
    for port in ports:
        if isinstance(port, range):
            list_port.update(list(port))
        else:
            list_port.add(port)
    return tuple(sorted(list_port))


def _check_address_with_rules(
        socket_rules: SocketRules,
        socket_kind: Kind,
        address: Tuple[str, int],  # Expect (hostname_or_ip_str, port_int)
        conn_direction: Direction):  # Expect IN or OUT constants
    """
    Checks if a given address and port are allowed for the specified connection directions
    based on the configured rules and the derived implicit default policy.
    (Docstring needs update for new socket_instance_family, socket_instance_proto args)
    """
    # logger.debug(
    #     "_check_address_with_rules(address=%s, conn_direction=%s, kind=%s)",
    #     address, conn_direction.name, socket_kind.name)
    hostname, destination_port = address

    # TODO: cache?
    if not isinstance(destination_port, int) or not (
            0 <= destination_port <= 65535):
        raise ValueError(f"Invalid port number: {destination_port}")

    unique_ips: List[Union[IPv4Address, IPv6Address]]
    use_hostname = False
    try:

        unique_ips = [ip_address(hostname)]
    except ValueError:
        try:
            # Resolve hostname to IP addresses using the socket instance's family, type, and proto
            infos = socket.getaddrinfo(hostname, None)
            use_hostname = True
        except socket.gaierror:
            # Fallback if the specific proto causes issues, try with proto=0 (OS default for family/type)
            # This might happen if self.proto is something specific but getaddrinfo needs a more general hint
            try:
                logger.debug(
                    "getaddrinfo failed with specific proto %s, retrying with proto=0")
                infos = socket.getaddrinfo(hostname, None,
                                           type=socket_kind, proto=0)
            except socket.gaierror:
                raise ValueError(
                    f"Invalid hostname or IP address (resolution failed): {hostname}")

        # %% Analyse ips
        ip_objects = []
        for res_family, _, _, _, sockaddr in infos:
            # sockaddr[0] is the IP address string
            addr_str = sockaddr[0]
            ip_objects.append(ip_address(addr_str))

        unique_ips = list(dict.fromkeys(ip_objects))
    if not unique_ips:
        raise ValueError(  # TODO: TU for that
            f"Invalid hostname or IP address (resolution failed): {hostname}")

    # %% Analyse rules
    for rule_type_to_check in (Action.DENY, Action.ALLOW):
        for ip_host in unique_ips:
            for (action,
                 (rule_kind, network_list, rule_ports_list),
                 rule_directions,
                 config) in socket_rules:
                if action == rule_type_to_check:
                    kind_match = (rule_kind != Kind.UNKNOWN) or (
                            socket_kind in rule_kind)

                    if kind_match:
                        if conn_direction in rule_directions:
                            if ip_host in network_list and destination_port in rule_ports_list:

                                if action == Action.DENY:
                                    if use_hostname:
                                        pysandboxes_logger.error(
                                            "Connection to '%s' (%s:%s) "
                                            "DENIED by explicit rule "
                                            "'%s' from %s",
                                            hostname, ip_host, destination_port,
                                            config.rule, format_ruleref(config)
                                        )
                                        raise RuleSocketConnectionRefusedError(
                                            f"Guard network connection to "
                                            f"{hostname!r} "
                                            f"({ip_host}:{destination_port}) "
                                            f"{action} by rule "
                                            f"{config.rule!r} "
                                            f"from {format_ruleref(config)})."
                                        )
                                    else:
                                        pysandboxes_logger.error(
                                            "Connection to [%s]:%s "
                                            "DENIED by explicit rule "
                                            "'%s' from %s",
                                            ip_host, destination_port,
                                            config.rule, format_ruleref(config)
                                        )
                                        raise RuleSocketConnectionRefusedError(
                                            f"Guard network connection to "
                                            f"[{ip_host}]:{destination_port} "
                                            f"{action} by rule "
                                            f"{config.rule!r} "
                                            f"from {format_ruleref(config)})."
                                        )

                                elif action == Action.ALLOW:
                                    if pysandboxes_logger.isEnabledFor(logging.DEBUG):
                                        if use_hostname:
                                            pysandboxes_logger.debug(
                                                "Connection to '%s' ([%s]:%s) "
                                                "ALLOW by explicit rule "
                                                "'%s' from %s",
                                                hostname, ip_host, destination_port,
                                                config.rule, format_ruleref(config)
                                            )
                                        else:
                                            pysandboxes_logger.debug(
                                                "Connection to [%s]:%s "
                                                "ALLOW by explicit rule "
                                                "'%s' from %s",
                                                ip_host, destination_port,
                                                config.rule, format_ruleref(config)
                                            )
                                    return
    try:
        ip_address(hostname)
        target = f'[{hostname}]:{destination_port}'
    except ValueError:
        target = (f"'[{hostname}]:{destination_port}' "
                  f"({' '.join([str(unique_ip) for unique_ip in unique_ips])}"
                  f"{destination_port}) ")

    pysandboxes_logger.error(
        "Connection to '%s' "
        "DENIED by implicit default policy.",
        target
    )
    raise RuleSocketConnectionRefusedError(
        f"Guard network connection to {str(target)!r} "
        f"DENIED by implicit default policy."
    )


_get_rules = lambda: []

# see _scoket.pyi
ReadableBuffer: TypeAlias = Buffer  # stable
_Address: TypeAlias = tuple[Any, ...] | str | ReadableBuffer
_RetAddress: TypeAlias = Any

_map_kind_to_str = {
    socket.SOCK_DGRAM: "udp",
    socket.SOCK_STREAM: "tcp",
}
_map_str_to_kind = {
    "udp": socket.SOCK_DGRAM,
    "tcp": socket.SOCK_STREAM,
}


# Not used
def _get_fammily(ip: str) -> int:
    ip_object = ip_address(ip)
    if ip_object.version == 4:
        familly = socket.AF_INET
    elif ip_object.version == 6:
        familly = socket.AF_INET6
    else:
        familly = 0
    return familly


class Guard_socket(socket.socket):
    """
    A custom socket class that enforces network rules to restrict connections.
    Rule string format: "net=ACTION|SOCKET_SPECS|NETWORK_STR|PORT_SPEC_STR|DIRECTION_STR"
    Example: "net=ALLOW|tcp|192.168.1.0/24|80,443|OUT"
    SOCKET_SPECS: "any", "tcp", "udp", or comma-separated combinations.
    """

    def _check_address(self,
                       address: Tuple[str, int],
                       conn_direction: Direction):
        _check_address_with_rules(_rules,
                                  Kind(self.type),
                                  address,
                                  conn_direction)

    def __init__(self,
                 family: int = socket.AF_INET,
                 type: int = socket.SOCK_STREAM,
                 proto: int = 0,
                 fileno: Optional[int] = None):
        # Ensure family and type are resolved if passed as enum members
        actual_family = family.value if isinstance(family,
                                                   socket.AddressFamily) else family
        actual_type = type.value if isinstance(type, socket.SocketKind) else type

        super().__init__(actual_family, actual_type, proto, fileno)
        # Note: self.family, self.type, self.proto are now available from the superclass

    def bind(self, address: Adresse_Type) -> None:
        # TODO: add unit test
        if (isinstance(address, tuple) and len(address) >= 2 and
                isinstance(address[0], str)
                and isinstance(address[1], int)):
            if is_learning_mode():
                add_learning_rule(
                    LearnSocketRule(
                        "bind",
                        Kind(self.type),
                        address[0],
                        int(address[1]),
                        Direction.IN,
                        (),  # dns
                    )
                )
            else:
                self._check_address((
                    str(address[0]),
                    int(address[1])),
                    conn_direction=Direction.IN)
        elif isinstance(address, str):  # AF_UNIX
            logger.debug(
                "Allowing bind to AF_UNIX address (not subject to IP rules): %s",
                address)
        else:
            logger.warning(
                "Unexpected address format for bind: %s. Skipping IP rule check.",
                address)
        super().bind(address)

    def connect(self, address: Adresse_Type) -> None:
        if (isinstance(address, tuple) and len(address) >= 2
                and isinstance(address[0], str)
                and isinstance(address[1], int)):
            if is_learning_mode():
                add_learning_rule(
                    LearnSocketRule(
                        "connect",
                        Kind(self.type),
                        address[0],
                        int(address[1]),
                        Direction.OUT,
                        ()  # dns
                    )
                )
            else:
                self._check_address((
                    str(address[0]),
                    int(address[1])),
                    conn_direction=Direction.OUT)
        elif isinstance(address, str):  # AF_UNIX
            logger.debug(
                "Allowing connect to AF_UNIX address (not subject to IP rules): %s",
                address)
        else:
            logger.warning(
                "Unexpected address format for connect: %s. Skipping IP rule check.",
                address)
            # FIX_RELEASE: unknown socket format
            assert False, (f"Unexpected address format for connect: "
                           f"{address}. Skipping IP rule check.")
        super().connect(address)

    def connect_ex(self, address: Adresse_Type) -> int:
        if isinstance(address, tuple) and len(address) >= 2 and isinstance(
                address[0], str) and isinstance(address[1], int):
            if is_learning_mode():
                add_learning_rule(
                    LearnSocketRule(
                        "connect_ex",
                        Kind(self.type),
                        address[0],
                        int(address[1]),
                        Direction.OUT,
                        ()  # dns
                    )
                )
            else:
                self._check_address((
                    str(address[0]),
                    int(address[1])),
                    conn_direction=Direction.OUT)
        elif isinstance(address, str):  # AF_UNIX
            logger.debug(
                "Allowing connect_ex to AF_UNIX address (not subject to IP rules): %s",
                address)
        else:
            logger.warning(
                "Unexpected address format for connect_ex: %s. Skipping IP rule check.",
                address)
        return super().connect_ex(address)

    def sendto(self, data: ReadableBuffer, address: _Address, /) -> int:
        if isinstance(address, tuple) and len(address) >= 2 and isinstance(
                address[0], str) and isinstance(address[1], int):
            if self.type == Kind.UDP.value:
                if is_learning_mode():
                    add_learning_rule(
                        LearnSocketRule(
                            "sendto",
                            Kind(self.type),
                            address[0],
                            int(address[1]),
                            Direction.OUT,
                            ()  # dns
                        )
                    )
                else:
                    self._check_address((
                        str(address[0]),
                        int(address[1])),
                        conn_direction=Direction.OUT)
            else:
                logger.debug("Invalide usage of sendto")
        return super().sendto(data, address)

    # def recvfrom(self, bufsize: int, flags: int = ..., /) -> tuple[bytes, _RetAddress]:
    #     # if is_learning_mode():
    #     #     add_learning_rule(
    #     #         LearnSocketRule(
    #     #             "sendto",
    #     #             "udp",
    #     #             address[0],
    #     #             address[1],
    #     #             IN,
    #     #             ()
    #     #         )
    #     #     )
    #     # else:
    #     #     self._check_address((str(address[0]), int(address[1])),
    #     #                             conn_direction=OUT)
    #     return super().recvfrom(bufsize, flags)


# %%
if "PYTEST_RUN_CONFIG" in os.environ:
    def _deactivate_guard_sockets():
        global _rules
        _rules = ()


def _wrap_socket_gethostbyname(func: Callable) -> Callable:
    @functools.wraps(func)
    def wrapper(name: str, *args, **kwargs):
        result = func(name, *args, **kwargs)
        if (isinstance(name, str) and name and
                is_learning_mode()):
            add_learning_rule(
                LearnSocketRule(
                    "gethostbyname",
                    Kind.UNKNOWN,
                    name,
                    0,
                    Direction.OUT,
                    (ip_address(result),),
                )
            )
        return result

    return wrapper


def _wrap_socket_gethostbyname_ex(func: Callable) -> Callable:
    @functools.wraps(func)
    def wrapper(name: str, *args, **kwargs):
        result = func(name, *args, **kwargs)
        if (isinstance(name, str) and name and
                is_learning_mode()):
            add_learning_rule(
                LearnSocketRule(
                    "gethostbyname_ex",
                    Kind.UNKNOWN,
                    name,
                    0,
                    Direction.OUT,
                    tuple(result[2])
                )
            )
        return result

    return wrapper


def _wrap_socket_getaddrinfo(func: Callable) -> Callable:
    @functools.wraps(func)
    def wrapper(host: bytes | str | None,
                port: bytes | str | int | None,
                family: int = 0,
                type: int = 0,
                proto: int = 0,
                flags: int = 0,
                *args, **kwargs
                ) -> list[
        tuple[
            socket.AddressFamily, socket.SocketKind,
            int,
            str, tuple[str, int] |
                 tuple[str, int, int, int]]]:
        result = func(host, port, family, type, proto, flags, *args, **kwargs)
        if (isinstance(host, str) and host and
                is_learning_mode()):
            add_learning_rule(
                LearnSocketRule(
                    "getaddrinfo",
                    Kind.UNKNOWN,
                    host,
                    int(port) if port is not None else 0,
                    Direction.OUT,
                    tuple({ip_address(info[4][0]) for info in result})
                )
            )
        return result

    return wrapper


def patch_rules() -> Dict[str, Callable]:
    return {
        "socket.socket":
            lambda x: Guard_socket,
        # FIXME: Use patch for method?
        # FIXME: patch gethostbyname() only if learn ?
        "socket.gethostbyname": _wrap_socket_gethostbyname,
        "socket.gethostbyname_ex": _wrap_socket_gethostbyname_ex,
        "socket.getaddrinfo": _wrap_socket_getaddrinfo,
    }


def activate_guard(rules: SocketRules) -> None:
    if not rules:
        return
    global _rules
    if _rules:
        raise RuntimeError("Guard_socket already activated.")
    _rules = rules


def _read_host_file() -> Tuple[
    Dict[str, Union[IPv4Address, IPv6Address]],
    Dict[Union[IPv4Address, IPv6Address], str]
]:
    dns: Dict[str, Union[IPv4Address, IPv6Address]] = {}
    inverse_dns: Dict[Union[IPv4Address, IPv6Address], str] = {}
    # Read the host file
    # Détecter le système d'exploitation pour trouver le bon chemin
    if sys.platform == "win32":
        system_root = os.environ.get("SystemRoot")
        if not system_root:
            system_root = r"C:\Windows"
        hosts_file = Path(system_root) / r"System32\drivers\etc\hosts"
    elif (sys.platform.startswith("linux") or
          sys.platform == "darwin" or
          sys.platform.startswith("freebsd") or
          sys.platform == "sunos"):
        hosts_file = Path("/etc/hosts")
    else:
        return {}
    if hosts_file.exists():
        host_lines = hosts_file.read_text().split("\n")
        for line in host_lines:
            if line.startswith("#"):
                continue
            line = line.strip()
            if line:
                ip, *hosts = line.split()
                if hosts:
                    inverse_dns[ip_address(ip)] = hosts[0]
                for host in hosts:
                    dns[host] = ip_address(ip)
    # Force localhost
    return dns, inverse_dns


def generate_rules(
        learn: Set[Any],
) -> List[str]:
    result = set()
    dns, inverse_dns = _read_host_file()

    # 1. Get dns info
    for learn_rule in filter(lambda x: isinstance(x, LearnSocketRule), learn):
        if learn_rule.fn in ("getaddrinfo", "gethostbyname", "gethostbyname_ex"):
            for ip in learn_rule.dns:
                inverse_dns[ip] = learn_rule.address
                dns[learn_rule.address]=ip

    # 2. Map access to dns
    by_destination = {}
    for learn_rule in filter(lambda x: isinstance(x, LearnSocketRule), learn):
        if learn_rule.fn not in ("getaddrinfo", "gethostbyname", "gethostbyname_ex"):
            if learn_rule.address in dns:
                destination = learn_rule.address
            else:
                ip = ip_address(learn_rule.address)
                if ip in inverse_dns:
                    destination = inverse_dns[ip]
                else:
                    if ip.version == 5:
                        mask = 32
                    elif ip.version == 6:
                        mask = 128
                    else:
                        mask = 0  # Uknown mask
                    if mask:
                        destination = f"{learn_rule.address}/{mask}"
                    else:
                        destination = learn_rule.address
            # Search alias in env
            port = str(learn_rule.port)  # FIXME: alias of port in env
            for k, v in os.environ.items():
                if v == destination:
                    destination = f"${{{k}}}"
            # Split by direction
            in_out = by_destination.get((destination, learn_rule.kind), ([], []))
            if learn_rule.direction is Direction.IN:
                in_out[0].append(learn_rule)
            else:
                in_out[1].append(learn_rule)
            by_destination[(destination, learn_rule.kind)] = in_out

    # 3. Generate rules

    # Try to find port alias
    key_for_port={}
    for k,v in os.environ.items():
        if "port" in k.lower():
            try:
                # Look like a port?
                int(v)
                key_for_port[int(v)] = f"${{{k}}}"
            except ValueError:
                pass  # Ignore
    for (destination, kind), (in_rules_for_dest,
                              out_rules_for_dest) in by_destination.items():
        # Agregate ports
        if in_rules_for_dest:
            in_ports = {key_for_port.get(rule.port,str(rule.port)) for rule in
                        in_rules_for_dest}  # Can not be a range
            result.add(
                f"net=ALLOW|{learn_rule.kind.name}|"
                f"{destination}|{','.join(in_ports)}|"
                f"{Direction.IN.name}"
            )
        if out_rules_for_dest:
            out_ports = {key_for_port.get(rule.port,str(rule.port)) for rule in
                        out_rules_for_dest}  # Can not be a range
            result.add(
                f"net=ALLOW|{learn_rule.kind.name}|"
                f"{destination}|{','.join(out_ports)}|"
                f"{Direction.OUT.name}"
            )
    return sorted(list(result))
